/**
 * Generates src/lib/imageSizes.ts — a map of asset file name → intrinsic pixel
 * size, read straight from the image headers in src/assets.
 *
 * Why: `<img>` needs width/height attributes so the browser can reserve the
 * right box before the bytes arrive (no layout shift, better LCP). Most images
 * on this site come from `import.meta.glob`, so the component only ever sees a
 * hashed URL and cannot know the dimensions. The generated map closes that gap;
 * `getImageSize()` in src/lib/imageSize.ts resolves a URL back to its size.
 *
 * Runs in `prebuild`, next to the sitemap generator. The output is committed so
 * a plain `vite build` (and the dev server) work without running this first.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, resolve, extname, basename, relative } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const assetsDir = resolve(__dirname, '../src/assets');
const outFile = resolve(__dirname, '../src/lib/imageSizes.ts');

const EXTENSIONS = new Set(['.png', '.jpg', '.jpeg', '.webp', '.gif']);

type Size = [number, number];

/** Reads the intrinsic size out of a PNG / GIF / WEBP / JPEG header. */
function readSize(buf: Buffer): Size | null {
  // PNG: IHDR width/height at a fixed offset
  if (buf.length > 24 && buf.readUInt32BE(0) === 0x89504e47) {
    return [buf.readUInt32BE(16), buf.readUInt32BE(20)];
  }

  // GIF: logical screen descriptor
  if (buf.length > 10 && buf.subarray(0, 3).toString('ascii') === 'GIF') {
    return [buf.readUInt16LE(6), buf.readUInt16LE(8)];
  }

  // WEBP: three container variants, each with its own layout
  if (
    buf.length > 30 &&
    buf.subarray(0, 4).toString('ascii') === 'RIFF' &&
    buf.subarray(8, 12).toString('ascii') === 'WEBP'
  ) {
    const format = buf.subarray(12, 16).toString('ascii');
    if (format === 'VP8 ') {
      return [buf.readUInt16LE(26) & 0x3fff, buf.readUInt16LE(28) & 0x3fff];
    }
    if (format === 'VP8L') {
      const bits = buf.readUInt32LE(21);
      return [(bits & 0x3fff) + 1, ((bits >> 14) & 0x3fff) + 1];
    }
    if (format === 'VP8X') {
      const width = buf[24] | (buf[25] << 8) | (buf[26] << 16);
      const height = buf[27] | (buf[28] << 8) | (buf[29] << 16);
      return [width + 1, height + 1];
    }
  }

  // JPEG: walk the segments until a start-of-frame marker
  if (buf.length > 4 && buf[0] === 0xff && buf[1] === 0xd8) {
    let i = 2;
    while (i + 9 < buf.length) {
      if (buf[i] !== 0xff) {
        i++;
        continue;
      }
      const marker = buf[i + 1];
      const isStartOfFrame =
        marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc;
      if (isStartOfFrame) {
        return [buf.readUInt16BE(i + 7), buf.readUInt16BE(i + 5)];
      }
      i += 2 + buf.readUInt16BE(i + 2);
    }
  }

  return null;
}

function walk(dir: string, files: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      walk(full, files);
    } else if (EXTENSIONS.has(extname(entry).toLowerCase())) {
      files.push(full);
    }
  }
  return files;
}

const files = walk(assetsDir).sort();
const sizes = new Map<string, Size>();
const collisions: string[] = [];
const unreadable: string[] = [];

for (const file of files) {
  const name = basename(file);
  const size = readSize(readFileSync(file));

  if (!size) {
    unreadable.push(relative(assetsDir, file));
    continue;
  }

  const existing = sizes.get(name);
  if (existing && (existing[0] !== size[0] || existing[1] !== size[1])) {
    // Same file name in two folders with different dimensions: a lookup by
    // name would be ambiguous, so neither entry is trustworthy.
    collisions.push(relative(assetsDir, file));
    sizes.delete(name);
    continue;
  }

  sizes.set(name, size);
}

const entries = [...sizes.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, [w, h]]) => `  '${name}': [${w}, ${h}],`)
  .join('\n');

const output = `// GENERATED by scripts/generate-image-sizes.ts — do not edit by hand.
// Run \`npx tsx scripts/generate-image-sizes.ts\` (or \`npm run build\`) to refresh.
//
// Maps an asset file name to its intrinsic [width, height] in pixels, so that
// components rendering globbed/hashed image URLs can still emit width and
// height attributes. Resolve a URL with getImageSize() from './imageSize'.

export const imageSizes: Record<string, [number, number]> = {
${entries}
};
`;

writeFileSync(outFile, output, 'utf-8');

console.log(`✅ image-sizes: ${sizes.size} assets → src/lib/imageSizes.ts`);
if (collisions.length > 0) {
  console.warn(
    `⚠️  image-sizes: ambiguous file names skipped (same name, different size):\n   ${collisions.join('\n   ')}`
  );
}
if (unreadable.length > 0) {
  console.warn(`⚠️  image-sizes: could not read dimensions:\n   ${unreadable.join('\n   ')}`);
}
